app/flask_blog/index/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import Form
from wtforms import TextField
from wtforms.validators import DataRequired, Email


class ContactForm(Form):
    email = TextField(
        'Email Address', validators=[DataRequired(), Email()])
    message = TextField('Message')


# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/__init__.py
# -*- coding: utf-8 -*-
import os
from pymongo import MongoClient
from flask import (Flask, g)
from flask_mail import Mail
from flask.ext.login import LoginManager
from flask.ext.debugtoolbar import DebugToolbarExtension
from flask_wtf.csrf import CsrfProtect
from werkzeug.local import LocalProxy

from . import config
from blog import Blog
from utils import datetime_filter, canonical_filter

root_path = os.environ.get('FLASK_BLOG_ROOT', None)
if root_path:
    app_cfg = {
        'template_folder': os.path.join(root_path, 'templates'),
        'static_folder': os.path.join(root_path, 'static'),
    }
else:
    app_cfg = {}

app = Flask(__name__, **app_cfg)
CsrfProtect(app)
login_manager = LoginManager()
login_manager.init_app(app)

app.debug = False

config.configure_app(app)

config.configure_logger(app)

login_manager.login_view = 'user.login'

blog_cache = Blog()
blog_cache.init_app(app)

app.jinja_env.filters['datetime'] = datetime_filter
app.jinja_env.filters['make_canonical'] = canonical_filter

mailer = Mail(app)


def get_database_connection():
    con = getattr(g, 'database_connection', None)
    if con is None:
        g.database_connection = con = MongoClient(app.config['MONGO_URI'])
        g.db = con.get_database(app.config['MONGO_DATABASE'])
    return g.db


@app.teardown_appcontext
def close_database_connection(error=None):
    if error is None:
        callbacks = getattr(g, 'on_teardown_callbacks', ())
        for callback in callbacks:
            callback()

    con = getattr(g, 'database_connection', None)
    if con is not None:
        con.close()

db = LocalProxy(get_database_connection)

toolbar = DebugToolbarExtension(app)

from . import models


@login_manager.user_loader
def load_user(user_id):
    return models.Users.from_id(user_id)

##############
# blueprints #
##############

from index.views import index_blueprint
from forward.views import forward_blueprint
from user.views import user_blueprint
from blog.views import blog_blueprint

app.register_blueprint(index_blueprint)
app.register_blueprint(forward_blueprint)
app.register_blueprint(user_blueprint)
app.register_blueprint(blog_blueprint)


def init_db():
    models.create_all_collections()


def drop_db():
    db.client.drop_database(app.config['MONGO_DATABASE'])


if __name__ == '__main__':
    app.run()

# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/blog/__init__.py
# -*- coding: utf-8 -*-
import markdown
from dateutil.parser import parse as dateparse
from os import listdir
from os.path import splitext, abspath, join as pjoin
from datetime import datetime

from ..utils import slugify


class Cache(object):

    def __init__(self, blog):
        self.filled = False
        self.blog = blog
        self.documents = []
        self.category_index = {}
        self.category_names = {}
        self.slug_index = {}

    def parse_meta(self, meta):
        res = {
            'title': '',
            'authors': [''],
            'date': datetime.now(),
            'summary': '',
            'categories': ['Default'],
            }
        for key, value in meta.iteritems():
            if key in ['date', 'updated']:
                res[key] = dateparse(' '.join(value))
            elif key in ['summary', 'title', 'slug']:
                res[key] = '\n'.join(value).strip()
            elif key in ['categories']:
                res['category_slugs'] = [slugify(c) for c in value]
                res[key] = value
            else:
                res[key] = value

        if 'slug' not in res:
            if 'title' in res:
                res['slug'] = slugify(res['title'])
            else:
                raise ValueError('No slug definition for blog entry found')
        if 'updated' not in res:
            res['updated'] = res['date']

        res['slug'] = res['slug'].lower()
        return res

    def _read(self, mdfile):
        md = markdown.Markdown(
            # 'markdown.extensions.extra',
            # 'markdown.extensions.admonition',
            extensions=[
                'markdown.extensions.meta'],
            output_format='html5')
        with open(mdfile, 'r') as fh:
            text = fh.read()
            html = md.convert(text)
            document = {
                'html': html}
            document.update(self.parse_meta(md.Meta))

        return document

    def cache_all_blogs(self):
        candidates = sorted(listdir(self.blog.blog_dir))
        mdfiles = [
            abspath(pjoin(self.blog.blog_dir, c)) for c in candidates if (
                splitext(c)[1] in ['.md', '.markdown', '.mdown'])]

        for i, mdfile in enumerate(mdfiles):
            document = self._read(mdfile)
            for cat in document['categories']:
                scat = slugify(cat)
                self.category_names[scat] = cat
                if scat in self.category_index:
                    cindex = self.category_index[scat]
                else:
                    cindex = self.category_index[scat] = []
                cindex.append(i)

            self.slug_index[document['slug']] = i

            self.documents.append(document)
        self.filled = True

    def get_blog(self, slug):
        if not self.filled:
            self.cache_all_blogs()

        slug_index = self.slug_index[slug]
        return self.documents[slug_index]

    def list_blogs(self, category=None):
        if not self.filled:
            self._cache_all_blogs()

        if category:
            return [self.documents[i] for i in self.category_index[category]]
        else:
            return self.documents


class Blog(object):

    def init_app(self, app, fill_cache=True):
        self.app = app
        # I really do not know, if we need to make this a local proxy or
        # something like that...
        self.cache = Cache(self)
        self.cache.cache_all_blogs()
        app.jinja_env.globals['blogs'] = self

    @property
    def blog_dir(self):
        return self.app.config.get('FLASK_BLOG_DIR', None)

    def get_blog(self, slug):
        """
        partial information about a blog entry
        """
        return self.cache.get_blog(slug)

    def list_blogs(self, category=None):
        """
        list all blog entries in a category, or in all categories
        """
        return self.cache.list_blogs(category)

    def get_category_name(self, category_slug):
        return self.cache.category_names[category_slug]

    def get_categories(self):
        return self.cache.category_names

# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/blog/views.py
# -*- coding: utf-8 -*-
from flask import (
    render_template, Blueprint, jsonify, abort, url_for, request)
from flask.ext.login import login_required
from werkzeug.contrib.atom import AtomFeed

from flask_blog import blog_cache

from ..utils import slugify

blog_blueprint = Blueprint('blog', __name__,)


@blog_blueprint.route('/blog/<category>/<slug>')
def blog(category, slug):
    try:
        blog = blog_cache.get_blog(slug)
        assert category in [slugify(c) for c in blog['categories']]
    except:
        abort(404)

    return render_template(
        'blog.html', category=category, blog=blog, menu={'select': 'blog'})


@blog_blueprint.route('/blog/', defaults={'category': None})
@blog_blueprint.route('/blog/<category>')
def category_listing(category):
    blogs = blog_cache.list_blogs(category=category)
    if category:
        category_name = blog_cache.get_category_name(category)
    else:
        category_name = 'All'

    return render_template(
        'blogs.html',
        category=category,
        category_name=category_name,
        category_blogs=blogs,
        menu={'select': 'blogs'})


@blog_blueprint.route('/api/reload/<slug>')
@login_required
def api_reload_blog(slug=None):
    return jsonify(result='ignored', slug=slug)


@blog_blueprint.route('/api/blog/feed')
def recent_feed():
    """
    Creates an RSS feed.

    Do not forget to put the following in your document

        <link href="{{ url_for('recent_feed') }}"
              rel="alternate"
              title="Recent Changes"
              type="application/atom+xml">
    """
    feed = AtomFeed(
        'Recent Articles',
        feed_url=request.url, url=request.url_root)
    articles = blog_cache.list_blogs()

    for article in articles:
        feed.add(
            article['title'], unicode(article['html']),
            content_type='html',
            author=article['authors'][0],
            url=url_for(
                'blog.blog',
                category=slugify(article['categories'][0]),
                slug=article['slug'],
                _external=True),
            updated=article['updated'],
            published=article['date'])

    return feed.get_response()
# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/forward/__init__.py
# -*- coding: utf-8 -*-

# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/index/__init__.py
# -*- coding: utf-8 -*-

# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/index/views.py
# -*- coding: utf-8 -*-
from flask import (
    render_template, Blueprint, current_app, request, redirect, flash, url_for,
    jsonify)

from ..mail import send_mail
from .forms import ContactForm
from ..utils import after_app_teardown


index_blueprint = Blueprint('index', __name__,)


def send_contact_mail(data):
    test = data.get('test', '')
    send_mail(
        subject='[CONTACT_FORM]{} message from {}'.format(
            test, data.get('email', '')),
        body=data.get('message'),
        recipients=[current_app.config.get('CONTACT_EMAIL')],
        reply_to=data.get('email', 'unknownemail@example.com'))


@index_blueprint.route('/contact.html')
def contact():
    form = ContactForm()
    return render_template('contact.html', form=form, menu={})


@index_blueprint.route('/')
@index_blueprint.route('/index.html')
def index():
    return render_template('index.html', menu={'select': None})


@index_blueprint.route('/publications.html')
def publications():
    pass


@index_blueprint.route('/contact_form', methods=['GET', 'POST'])
def contact_form():
    data = request.form

    @after_app_teardown
    def send_mail():
        send_contact_mail(data)

    flash('Thank you for your feedback.', 'success')
    return redirect(url_for('.index'))


@index_blueprint.route('/api/minimal_css')
def minimal_css():
    """
    This returns a list of options for the 'above-the-fold' gulp task, that
    creates critical css files.

    Include source code of the following syntax into your jinja templates, in
    order to inject the files:

        {% block above_the_fold_css %}
        {# inject_critical:index.critical.css: #}
        {% endblock above_the_fold_css %}
    """
    criticals = [
        {
            'filename': 'index.critical.css',
            'url': url_for('index.index'),
        }, {
            'filename': 'blog_category.critical.css',
            'url': url_for('blog.category_listing'),
        }, {
            'filename': 'blog.critical.css',
            'url': url_for(
                'blog.blog', category='category-1', slug='first-blog'),
        }]
    return jsonify(list=criticals)

# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/user/views.py
# -*- coding: utf-8 -*-

from passlib.hash import bcrypt
from flask import (
    Blueprint, request, redirect, render_template,
    url_for, flash, abort)
from flask.ext.login import (
    login_required, logout_user, login_user, current_user)
from .forms import (
    TrialSignupForm, LoginForm, NoPasswordForm, NewPasswordForm)
import itsdangerous

from flask_blog import models
from ..utils import redirect_back, is_safe_url, after_app_teardown

user_blueprint = Blueprint('user', __name__)


@user_blueprint.route('/user/logout')
@login_required
def logout():
    current_user.authentication_change(False)

    logout_user()
    flash('You are logged out now! Thank you for visiting.', 'success')
    return redirect(url_for('index.index'))


@user_blueprint.route('/user/signup.html', methods=['GET', 'POST'])
def signup():
    form = TrialSignupForm(request.form)
    if form.validate_on_submit():

        user = models.Users.add(
            name=form.name.data,
            email=form.email.data,
            wants_newsletter=form.wants_newsletter.data)

        user.authentication_change(True)

        # ## ATTENTION:  Currently the user is logged in right after sign up.
        login_user(user)

        flash('You are logged in now.', 'success')
        flash(
            'If you want to log in from a different computer, '
            'activate your account with the activation email, we '
            'sent to you.', 'info')

        return redirect(url_for('index.index'))
    return render_template('signup.html', form=form, menu={})


@user_blueprint.route('/user/login.html', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():

        user = models.Users.from_username_or_email(form.user.data)

        if not user:
            form.user.errors.append('Invalid username or email.')
            return render_template('login.html', form=form, menu={})

        if not user.password:
            flash('There is no password associated with your account.  '
                  'Please activate it by clicking on the link in your '
                  'activation email.', 'error')
            return redirect(
                url_for(
                    'user.no_password',
                    next=request.args.get('next')))

        if bcrypt.verify(
                form.password.data, user.password):
            user.authentication_change(True)
            login_user(user)
            flash('You are successfully logged in.  Welcome!', 'success')
            return redirect_back('index.index')
        else:
            form.password.errors.append('Invalid password')
            return render_template('login.html', form=form, menu={})

    return render_template('login.html', form=form, menu={})


@user_blueprint.route('/user/forgot_password.html', methods=['GET', 'POST'])
def forgot_password():
    form = NoPasswordForm(request.form)

    if form.validate_on_submit():

        user = models.Users.from_username_or_email(form.user.data)

        if not user:
            form.user.errors.append('Invalid username or email address.')
            return render_template('forgot_password.html', form=form, menu={})

        user.set_password(None)

        @after_app_teardown
        def send_activation():
            user.send_activation_email(
                next=request.args.get('next'), forgot_password=True)

        flash(
            'We reset your password and sent a re-activation email to '
            'your email address.', 'success')
        return redirect_back('user.login')

    return render_template('forgot_password.html', form=form, menu={})


@user_blueprint.route('/user/no_password.html', methods=['GET', 'POST'])
def no_password():
    form = NoPasswordForm(request.form)
    if form.validate_on_submit():

        user = models.Users.from_username_or_email(form.user.data)

        if not user:
            form.user.errors.append('Invalid username or email address.')
            return render_template('no_password.html', form=form, menu={})

        @after_app_teardown
        def send_activation():
            user.send_activation_email(next=request.args.get('next'))

        flash(
            'We sent a new activation email to your email address.', 'success')

        return redirect_back('index.index')

    return render_template('no_password.html', form=form, menu={})


@user_blueprint.route('/user/login_required')
@login_required
def test_login_required():
    return repr(current_user)


@user_blueprint.route(
    '/user/activate/<activation_hash>',
    methods=['GET', 'POST'])
def activation(activation_hash):
    form = NewPasswordForm(request.form)

    try:
        uid = models.serializer.loads(
            activation_hash, salt=models.ACTIVATION_SALT)
    except itsdangerous.BadSignature:
        abort(404)

    user = models.Users.from_id(uid)

    if not user:
        flash('Could not validate the request', 'error')
        abort(404)

    user.email_validation_change(True)

    if user.password:
        next = request.args.get('next')
        if not is_safe_url(next):
            abort(400)

        next = next or url_for('index.index')

        return render_template(
            'activation_with_password.html', next=next, menu={})

    if form.validate_on_submit():

        user.set_password(bcrypt.encrypt(form.password.data), True)

        login_user(user)

        return redirect(
            url_for(
                'user.activation',
                activation_hash=activation_hash,
                **request.args))

    next = request.args.get('next')
    return render_template(
        'activation_no_password.html',
        uid=uid, activation_hash=activation_hash, next=next, form=form,
        menu={})


@user_blueprint.route('/user/settings')
def settings():
    pass


@user_blueprint.route('/admin')
@login_required
def admin():
    """ dummy function to test a login_required call """
    return render_template('admin.html', menu={})

# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/templates/activation_no_password.html
{%- import "_libs/wtf.html" as wtf -%}
{% extends "_bases/_headfoot_js.html" -%}

{% block upper_title %}
Email address is verified
{% endblock upper_title %}

{% block topbar %}
{% endblock topbar %}

{% block content %}
<div class="row">
  <h2>Please select a password for your account, before you continue...</h2>
</div>
<form action="{{url_for('user.activation', uid=uid, activation_hash=activation_hash)}}" method="post" accept-charset="utf-8" data-abide>
  {{ form.csrf_token }}
  <div class="row">
    <div class="columns medium-9">
      <label>Password:
        <input type="password" name="password" id="password" value="" required />
      </label>
      {{ wtf.wtf_errors(form.password, 'Please provide a valid password with at least 6 characters.')|safe }}
    </div>
    <div class="medium-9 columns">
      <label>Confirm password:
        <input type="password" name="confirm" id="confirm" value="" required data-equalto="password" />
      </label>
      {{ wtf.wtf_errors(form.confirm, 'The passwords need to match.')|safe }}<br />
    </div>
    <div class="medium-3 columns">
      <input type="hidden" value="{{next or ''}}" name="next" id="next"/>
      <input type="submit" class="button" name="submit" id="submit" value="Set passwords" />
    </div>
  </div>
</form>
{% endblock content %}

{% block footer %}
{% endblock footer %}

{# vim: set ft=htmljinja sw=2 et spell spelllang=en: #}

app/flask_blog/templates/activation_with_password.html
{% extends "_bases/_headfoot_js.html" -%}

{% block head %}
  <meta http-equiv="refresh" content="4;url={{next}}" />
  {{ super() }}
{% endblock head %}

{% block upper_title %}
Account is activated.
{% endblock upper_title %}

{% block topbar %}
{% endblock topbar %}

{% block content %}
<div class="row">
  Your email is verified and you are logged in now.
</div>
<div class="row">
  Click on this
  <a href="{{next}}">link</a> if you are not redirected automatically in a few
  seconds.
</div>
{% endblock content %}

{# vim: set ft=htmljinja sw=2 et spell spelllang=en: #}

app/flask_blog/templates/admin.html
{% extends "_bases/_headfoot_js.html" -%}
{% block content %}

<div class="row">
 <div class="center">
  <h1>Administration</h1>
</div>

{% endblock content %}

{# vim: set ft=htmljinja sw=2 et spell spelllang=en: #}

app/flask_blog/templates/blog.html
{% extends "_bases/_critical_path.html" -%}

{% block upper_title %}
<h1>{{ blog.title }}</h1>
{% endblock upper_title %}

{% block above_the_fold_css %}
{# inject_critical:blog.critical.css: #}
{% endblock above_the_fold_css %}

{% block content %}
<div class="author_info">
  <span class="writtenby">
    by
    <ul>
      {% for author in blog.authors -%}
      <li>{{ author }}</li>
      {%- endfor %}
    </ul>
  </span>
  <div class="published-dates">
    published on {{ blog.date | datetime }}<br />
    {% if blog.updated != blog.date %}
    last update on {{ blog.updated | datetime }}
    {% endif %}
  </div>
</div>

<div class="blog-content">
  <div class="main">
    {{ blog.html | safe }}
  </div>
  <div class="side">
    Other articles:
    <ul>
    {% for b in blogs.list_blogs(category) %}
    {% if blog.slug != b.slug %}
    <li><a href="{{url_for('blog.blog', category=category, slug=b.slug)}}">
        {{b.title}}
    </li>
    {% endif %}
    {% endfor %}
    </ul>
  </div>
</div>

<script id="below-the-fold">
loadCSS('/static/styles/main.css', window.document.getElementById('below-the-fold'));
</script>
<noscript>
<!-- build:css /static/styles/main.css media="all" async -->
<link rel="stylesheet" href="/static_gen/styles/main.css" media="all" async />
<!-- endbuild -->
</noscript>
{% endblock content %}

{# vim: set ft=htmljinja sw=2 et spell spelllang=en: #}

app/flask_blog/templates/blogs.html
{% extends "_bases/_critical_path.html" %}

{% block upper_title %}
<h1>{{ category_name }} blogs</h1>
{% endblock upper_title %}

{% block above_the_fold_css %}
{# inject_critical:blog_category.critical.css: #}
{% endblock above_the_fold_css %}

{% block content %}
  <div class="blog-cards">
    {% for blog in category_blogs %}
    <section>
      {% if not category %}
      {% set bcategory = blog.category_slugs[0] %}
      {% else %}
      {% set bcategory = category %}
      {% endif %}
      {% set target = url_for('blog.blog', category=bcategory, slug=blog.slug) %}
      <h1>{{blog.title}}</h1>
      <p class="summary">{{blog.summary}}</p>
      <a role="button" class="read-more btn btn-primary" href="{{ target }}">Read more...
      </a>
      <span class="last_update">{{blog.updated | datetime}}</span>
    </section>
    </hr>
    {% endfor %}
  </div>
<script id="below-the-fold">
loadCSS('/static/styles/main.css', window.document.getElementById('below-the-fold'));
</script>
<noscript>
<!-- build:css /static/styles/main.css media="all" async -->
<link rel="stylesheet" href="/static_gen/styles/main.css" media="all" async />
<!-- endbuild -->
</noscript>
{% endblock content %}

{# vim: set ft=htmljinja sw=2 et spell spelllang=en: #}

app/flask_blog/templates/contact.html
{% extends "_bases/_headfoot_js.html" -%}
{% block upper_title -%}
Contact form
{% endblock upper_title -%}

{% block content %}
<div class="row">
  <div class="columns small-12">
    <h3>
      Please provide your email address and send us your question.  We will get
back to you as soon as possible.
    </h3>

    <form class="footer-form" action="{{url_for('index.contact_form')}}" method="post" data-abide>
      {{ form.csrf_token }}
      <div class="row">
        <div class="small-12 columns">
          <label>
            <label for="email" class="contact">Email:</label>
            <input type="email" name="email" id="email" placeholder="Email Address" required />
          </label>
          <small class="error">Please fill in a valid email address.</small>
        </div>
      </div>
      <div class="row">
        <div class="small-12 columns">
          <label>Message:
            <textarea rows="5" name="message" id="message" placeholder="Message"></textarea>
          </label>
        </div>
      </div>

      <div class="row">
        <div class="small-12">
          <button class="submit round" type="submit" value="Submit">Send</button>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock content %}
{# vim: set ft=htmljinja sw=2 et spell spelllang=en: #}

app/flask_blog/templates/forgot_password.html
{%- import "_libs/wtf.html" as wtf -%}
{% extends "_bases/_headfoot_js.html" -%}

{% block upper_title %}
Password forgotten
{% endblock upper_title %}

{% block content %}
<form action="{{url_for('user.forgot_password')}}" method="post" accept-charset="utf-8" data-abide>
  {{ form.csrf_token }}
  <div class="row">
    <div class="columns medium-9">
      <label>Username or email:
        <input type="text" name="user" id="user" value="" required />
      </label>
      {{ wtf.wtf_errors(form.user, 'Please provide your username or your registered email address.')|safe }}
    </div>
    <div class="medium-3 columns">
      <input type="submit" class="button" name="submit" id="submit" value="Reset password." />
    </div>
    <div class="small-12 columns">
      <ul>
        <li>
          <a href="{{url_for('user.signup')}}">You are not registered yet?  Sign up for an account. It's free.</a>
        </li>
      </ul>
    </div>
  </div>
</form>
{% endblock content %}

{# vim: set ft=htmljinja sw=2 et spell spelllang=en: #}

app/flask_blog/templates/index.html
{% extends "_bases/_critical_path.html" -%}

{% block head %}
{{ super() }}
<style type="text/css" media="screen">
body {
  height: 100%;
}
</style>
{% endblock head %}

{% block above_the_fold_css %}
{# inject_critical:index.critical.css: #}
{% endblock above_the_fold_css %}

{% block header %}
{# <h1>Index page</h1> #}
{% endblock header %}

{% block content %}
<div class="jumbotron">
  <p class="text-center">
  This is slowly but steadily becoming a
  <a href="{{url_for('blog.category_listing', category='web-development')}}">
     blog!
  </a>
  {#
  creating products he belives in,
  #}
  </p>
</div>

<script id="below-the-fold">
loadCSS('/static_gen/styles/main.css', window.document.getElementById('below-the-fold'));
</script>
<noscript>
<!-- build:css -->
<link rel="stylesheet" href="/static_gen/styles/main.css" media="all" async />
<!-- endbuild -->
</noscript>
{% endblock content %}

{# vim: set ft=htmljinja sw=2 et spell spelllang=en: #}

app/flask_blog/templates/login.html
{%- import "_libs/wtf.html" as wtf -%}
{% extends "_bases/_headfoot_js.html" -%}

{% block upper_title %}
Log in to your account
{% endblock upper_title %}

{% block content %}
<form action="{{url_for('user.login')}}" method="post" accept-charset="utf-8" data-abide>
  {{ form.csrf_token }}
  <div class="row">
    <div class="columns medium-9">
      <label>Username or email:
        <input type="text" name="user" id="user" value="{{initial_user or ''}}" required />
      </label>
      {{ wtf.wtf_errors(form.user, 'Please provide your username or your registered email address.')|safe }}
    </div>
    <div class="medium-9 columns">
      <label>Password:
        <input type="password" name="password" id="password" value="" required />
      </label>
      {{ wtf.wtf_errors(form.password, '')|safe }}
    </div>
    <div class="medium-3 columns">
      <input type="hidden" value="{{next or ''}}" name="next" id="next"/>
      <input type="submit" class="button" name="submit" id="submit" value="Log in" />
    </div>
  </div>
</form>
  <div class="row">
    <div class="small-12 columns">
      <ul>
        <li>
          <a href="{{url_for('user.forgot_password')}}">I forgot my password.</a>
        </li>
        <li>
          <a href="{{url_for('user.no_password')}}">I do not have a password.</a>
        </li>
        <li>
          <a href="{{url_for('user.signup')}}">Sign up for an account. It's free.</a>
        </li>
      </ul>
    </div>
  </div>
{% endblock content %}

{# vim: set ft=htmljinja sw=2 et spell spelllang=en: #}

app/flask_blog/templates/no_password.html
{%- import "_libs/wtf.html" as wtf -%}
{% extends "_bases/_headfoot_js.html" -%}

{% block upper_title %}
Set a password
{% endblock upper_title %}

{% block content %}
<div class="row">
 <div class="columns small-12">
   After signing up, we sent you an email with an activation link.  Please
   click on this link, or request a new activation email.
 </div>
</div>
<form action="{{url_for('user.forgot_password')}}" method="post" accept-charset="utf-8" data-abide>
  {{ form.csrf_token }}
  <div class="row">
    <div class="columns medium-9">
      <label>Username or email:
        <input type="text" name="user" id="user" value="" required />
      </label>
      {{ wtf.wtf_errors(form.user, 'Please provide your username or your registered email address.')|safe }}<br />
    </div>
    <div class="medium-3 columns">
      <input type="submit" class="button" name="submit" id="submit" value="Resend activation mail" />
    </div>
    <div class="small-12 columns">
      <ul>
        <li>
          <a href="{{url_for('user.signup')}}">You are not registered yet?  Sign up for an account. It's free.</a>
        </li>
      </ul>
    </div>
  </div>
</form>
{% endblock content %}

{# vim: set ft=htmljinja sw=2 et spell spelllang=en: #}

app/flask_blog/templates/signup.html
{%- import "_libs/wtf.html" as wtf -%}
{% extends "_bases/_headfoot_js.html" -%}

{% block upper_title %}
Sign up for an account.
{% endblock upper_title %}

{% block content %}
<form action="{{url_for('user.signup')}}" method="post" accept-charset="utf-8" data-abide>
  {{ form.csrf_token }}
  <div class="row">
    <div class="full">
      <label>Name:
        <input type="text" name="name" id="name" value="" required />
      </label>
      {{ wtf.wtf_errors(form.name, 'Please fill in your name in the form. Thank you!')|safe }}<br />
    </div>
    <div class="full">
      <label>Email:
        <input type="email" name="email" placeholder="youremail@address.com" id="email" value="" required />
      </label>
      {{ wtf.wtf_errors(form.email, 'An email address is required.')|safe }}<br />
    </div>
    <div class="full">
      <input type="checkbox" name="wants_newsletter" />
      <label>
        Send me newsletter updates.
      </label>
    </div>
    <div class="full">
      <input type="submit" class="button" name="submit" id="submit" value="Sign up!" />
    </div>
  </div>
</form>

<p>
  <a href="{{url_for('user.login')}}">Already have an account?  Login here.</a>
</p>

{% endblock content %}

{# vim: set ft=htmljinja sw=2 et spell spelllang=en: #}

app/flask_blog/templates/site-verification.html
google-site-verification: {{site-verification}}

app/flask_blog/templates/test.html
{% extends "_bases/_headfoot_js.html" %}
{% block head %}
{{ super() }}
    <!-- build:css /static/styles/colors.css -->
    <link rel="stylesheet" href="/static_gen/styles/colors.css" media="all">
    <!-- endbuild -->
{% endblock head %}

{% block content %}
B {{config.DATABASE}}
C {{request.endpoint}}

<h1>Colors</h1>
{% for color in ['brand-primary', 'brand-success', 'brand-info', 'brand-warning', 'brand-danger'] %}
  <p class="{{color}}">{{color}}</p>
{% endfor %}
{% endblock %}
{# vim: set ft=htmljinja sw=2 et spell spelllang=en: #}