app/flask_blog/index/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import Form
from wtforms import TextField
from wtforms.validators import DataRequired, Email


class ContactForm(Form):
    email = TextField(
        'Email Address', validators=[DataRequired(), Email()])
    message = TextField('Message')


# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/__init__.py
# -*- coding: utf-8 -*-
import os
from pymongo import MongoClient
from flask import (Flask, g)
from flask_mail import Mail
from flask.ext.login import LoginManager
from flask.ext.debugtoolbar import DebugToolbarExtension
from flask_wtf.csrf import CsrfProtect
from werkzeug.local import LocalProxy

from . import config
from blog import Blog
from utils import datetime_filter, canonical_filter

root_path = os.environ.get('FLASK_BLOG_ROOT', None)
if root_path:
    app_cfg = {
        'template_folder': os.path.join(root_path, 'templates'),
        'static_folder': os.path.join(root_path, 'static'),
    }
else:
    app_cfg = {}

app = Flask(__name__, **app_cfg)
CsrfProtect(app)
login_manager = LoginManager()
login_manager.init_app(app)

app.debug = False

config.configure_app(app)

config.configure_logger(app)

login_manager.login_view = 'user.login'

blog_cache = Blog()
blog_cache.init_app(app)

app.jinja_env.filters['datetime'] = datetime_filter
app.jinja_env.filters['make_canonical'] = canonical_filter

mailer = Mail(app)


def get_database_connection():
    con = getattr(g, 'database_connection', None)
    if con is None:
        g.database_connection = con = MongoClient(app.config['MONGO_URI'])
        g.db = con.get_database(app.config['MONGO_DATABASE'])
    return g.db


@app.teardown_appcontext
def close_database_connection(error=None):
    if error is None:
        callbacks = getattr(g, 'on_teardown_callbacks', ())
        for callback in callbacks:
            callback()

    con = getattr(g, 'database_connection', None)
    if con is not None:
        con.close()

db = LocalProxy(get_database_connection)

toolbar = DebugToolbarExtension(app)

from . import models


@login_manager.user_loader
def load_user(user_id):
    return models.Users.from_id(user_id)

##############
# blueprints #
##############

from index.views import index_blueprint
from forward.views import forward_blueprint
from user.views import user_blueprint
from blog.views import blog_blueprint

app.register_blueprint(index_blueprint)
app.register_blueprint(forward_blueprint)
app.register_blueprint(user_blueprint)
app.register_blueprint(blog_blueprint)


def init_db():
    models.create_all_collections()


def drop_db():
    db.client.drop_database(app.config['MONGO_DATABASE'])


if __name__ == '__main__':
    app.run()

# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/blog/__init__.py
# -*- coding: utf-8 -*-
import markdown
from dateutil.parser import parse as dateparse
from os import listdir
from os.path import splitext, abspath, join as pjoin
from datetime import datetime

from ..utils import slugify


class Cache(object):

    def __init__(self, blog):
        self.filled = False
        self.blog = blog
        self.documents = []
        self.category_index = {}
        self.category_names = {}
        self.slug_index = {}

    def parse_meta(self, meta):
        res = {
            'title': '',
            'authors': [''],
            'date': datetime.now(),
            'summary': '',
            'categories': ['Default'],
            }
        for key, value in meta.iteritems():
            if key in ['date', 'updated']:
                res[key] = dateparse(' '.join(value))
            elif key in ['summary', 'title', 'slug']:
                res[key] = '\n'.join(value).strip()
            elif key in ['categories']:
                res['category_slugs'] = [slugify(c) for c in value]
                res[key] = value
            else:
                res[key] = value

        if 'slug' not in res:
            if 'title' in res:
                res['slug'] = slugify(res['title'])
            else:
                raise ValueError('No slug definition for blog entry found')
        if 'updated' not in res:
            res['updated'] = res['date']

        res['slug'] = res['slug'].lower()
        return res

    def _read(self, mdfile):
        md = markdown.Markdown(
            # 'markdown.extensions.extra',
            # 'markdown.extensions.admonition',
            extensions=[
                'markdown.extensions.meta'],
            output_format='html5')
        with open(mdfile, 'r') as fh:
            text = fh.read()
            html = md.convert(text)
            document = {
                'html': html}
            document.update(self.parse_meta(md.Meta))

        return document

    def cache_all_blogs(self):
        candidates = sorted(listdir(self.blog.blog_dir))
        mdfiles = [
            abspath(pjoin(self.blog.blog_dir, c)) for c in candidates if (
                splitext(c)[1] in ['.md', '.markdown', '.mdown'])]

        for i, mdfile in enumerate(mdfiles):
            document = self._read(mdfile)
            for cat in document['categories']:
                scat = slugify(cat)
                self.category_names[scat] = cat
                if scat in self.category_index:
                    cindex = self.category_index[scat]
                else:
                    cindex = self.category_index[scat] = []
                cindex.append(i)

            self.slug_index[document['slug']] = i

            self.documents.append(document)
        self.filled = True

    def get_blog(self, slug):
        if not self.filled:
            self.cache_all_blogs()

        slug_index = self.slug_index[slug]
        return self.documents[slug_index]

    def list_blogs(self, category=None):
        if not self.filled:
            self._cache_all_blogs()

        if category:
            return [self.documents[i] for i in self.category_index[category]]
        else:
            return self.documents


class Blog(object):

    def init_app(self, app, fill_cache=True):
        self.app = app
        # I really do not know, if we need to make this a local proxy or
        # something like that...
        self.cache = Cache(self)
        self.cache.cache_all_blogs()
        app.jinja_env.globals['blogs'] = self

    @property
    def blog_dir(self):
        return self.app.config.get('FLASK_BLOG_DIR', None)

    def get_blog(self, slug):
        """
        partial information about a blog entry
        """
        return self.cache.get_blog(slug)

    def list_blogs(self, category=None):
        """
        list all blog entries in a category, or in all categories
        """
        return self.cache.list_blogs(category)

    def get_category_name(self, category_slug):
        return self.cache.category_names[category_slug]

    def get_categories(self):
        return self.cache.category_names

# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/blog/views.py
# -*- coding: utf-8 -*-
from flask import (
    render_template, Blueprint, jsonify, abort, url_for, request)
from flask.ext.login import login_required
from werkzeug.contrib.atom import AtomFeed

from flask_blog import blog_cache

from ..utils import slugify

blog_blueprint = Blueprint('blog', __name__,)


@blog_blueprint.route('/blog/<category>/<slug>')
def blog(category, slug):
    try:
        blog = blog_cache.get_blog(slug)
        assert category in [slugify(c) for c in blog['categories']]
    except:
        abort(404)

    return render_template(
        'blog.html', category=category, blog=blog, menu={'select': 'blog'})


@blog_blueprint.route('/blog/', defaults={'category': None})
@blog_blueprint.route('/blog/<category>')
def category_listing(category):
    blogs = blog_cache.list_blogs(category=category)
    if category:
        category_name = blog_cache.get_category_name(category)
    else:
        category_name = 'All'

    return render_template(
        'blogs.html',
        category=category,
        category_name=category_name,
        category_blogs=blogs,
        menu={'select': 'blogs'})


@blog_blueprint.route('/api/reload/<slug>')
@login_required
def api_reload_blog(slug=None):
    return jsonify(result='ignored', slug=slug)


@blog_blueprint.route('/api/blog/feed')
def recent_feed():
    """
    Creates an RSS feed.

    Do not forget to put the following in your document

        <link href="{{ url_for('recent_feed') }}"
              rel="alternate"
              title="Recent Changes"
              type="application/atom+xml">
    """
    feed = AtomFeed(
        'Recent Articles',
        feed_url=request.url, url=request.url_root)
    articles = blog_cache.list_blogs()

    for article in articles:
        feed.add(
            article['title'], unicode(article['html']),
            content_type='html',
            author=article['authors'][0],
            url=url_for(
                'blog.blog',
                category=slugify(article['categories'][0]),
                slug=article['slug'],
                _external=True),
            updated=article['updated'],
            published=article['date'])

    return feed.get_response()
# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/forward/__init__.py
# -*- coding: utf-8 -*-

# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/index/__init__.py
# -*- coding: utf-8 -*-

# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/index/views.py
# -*- coding: utf-8 -*-
from flask import (
    render_template, Blueprint, current_app, request, redirect, flash, url_for,
    jsonify)

from ..mail import send_mail
from .forms import ContactForm
from ..utils import after_app_teardown


index_blueprint = Blueprint('index', __name__,)


def send_contact_mail(data):
    test = data.get('test', '')
    send_mail(
        subject='[CONTACT_FORM]{} message from {}'.format(
            test, data.get('email', '')),
        body=data.get('message'),
        recipients=[current_app.config.get('CONTACT_EMAIL')],
        reply_to=data.get('email', 'unknownemail@example.com'))


@index_blueprint.route('/contact.html')
def contact():
    form = ContactForm()
    return render_template('contact.html', form=form, menu={})


@index_blueprint.route('/')
@index_blueprint.route('/index.html')
def index():
    return render_template('index.html', menu={'select': None})


@index_blueprint.route('/publications.html')
def publications():
    pass


@index_blueprint.route('/contact_form', methods=['GET', 'POST'])
def contact_form():
    data = request.form

    @after_app_teardown
    def send_mail():
        send_contact_mail(data)

    flash('Thank you for your feedback.', 'success')
    return redirect(url_for('.index'))


@index_blueprint.route('/api/minimal_css')
def minimal_css():
    """
    This returns a list of options for the 'above-the-fold' gulp task, that
    creates critical css files.

    Include source code of the following syntax into your jinja templates, in
    order to inject the files:

        {% block above_the_fold_css %}
        {# inject_critical:index.critical.css: #}
        {% endblock above_the_fold_css %}
    """
    criticals = [
        {
            'filename': 'index.critical.css',
            'url': url_for('index.index'),
        }, {
            'filename': 'blog_category.critical.css',
            'url': url_for('blog.category_listing'),
        }, {
            'filename': 'blog.critical.css',
            'url': url_for(
                'blog.blog', category='category-1', slug='first-blog'),
        }]
    return jsonify(list=criticals)

# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/user/views.py
# -*- coding: utf-8 -*-

from passlib.hash import bcrypt
from flask import (
    Blueprint, request, redirect, render_template,
    url_for, flash, abort)
from flask.ext.login import (
    login_required, logout_user, login_user, current_user)
from .forms import (
    TrialSignupForm, LoginForm, NoPasswordForm, NewPasswordForm)
import itsdangerous

from flask_blog import models
from ..utils import redirect_back, is_safe_url, after_app_teardown

user_blueprint = Blueprint('user', __name__)


@user_blueprint.route('/user/logout')
@login_required
def logout():
    current_user.authentication_change(False)

    logout_user()
    flash('You are logged out now! Thank you for visiting.', 'success')
    return redirect(url_for('index.index'))


@user_blueprint.route('/user/signup.html', methods=['GET', 'POST'])
def signup():
    form = TrialSignupForm(request.form)
    if form.validate_on_submit():

        user = models.Users.add(
            name=form.name.data,
            email=form.email.data,
            wants_newsletter=form.wants_newsletter.data)

        user.authentication_change(True)

        # ## ATTENTION:  Currently the user is logged in right after sign up.
        login_user(user)

        flash('You are logged in now.', 'success')
        flash(
            'If you want to log in from a different computer, '
            'activate your account with the activation email, we '
            'sent to you.', 'info')

        return redirect(url_for('index.index'))
    return render_template('signup.html', form=form, menu={})


@user_blueprint.route('/user/login.html', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():

        user = models.Users.from_username_or_email(form.user.data)

        if not user:
            form.user.errors.append('Invalid username or email.')
            return render_template('login.html', form=form, menu={})

        if not user.password:
            flash('There is no password associated with your account.  '
                  'Please activate it by clicking on the link in your '
                  'activation email.', 'error')
            return redirect(
                url_for(
                    'user.no_password',
                    next=request.args.get('next')))

        if bcrypt.verify(
                form.password.data, user.password):
            user.authentication_change(True)
            login_user(user)
            flash('You are successfully logged in.  Welcome!', 'success')
            return redirect_back('index.index')
        else:
            form.password.errors.append('Invalid password')
            return render_template('login.html', form=form, menu={})

    return render_template('login.html', form=form, menu={})


@user_blueprint.route('/user/forgot_password.html', methods=['GET', 'POST'])
def forgot_password():
    form = NoPasswordForm(request.form)

    if form.validate_on_submit():

        user = models.Users.from_username_or_email(form.user.data)

        if not user:
            form.user.errors.append('Invalid username or email address.')
            return render_template('forgot_password.html', form=form, menu={})

        user.set_password(None)

        @after_app_teardown
        def send_activation():
            user.send_activation_email(
                next=request.args.get('next'), forgot_password=True)

        flash(
            'We reset your password and sent a re-activation email to '
            'your email address.', 'success')
        return redirect_back('user.login')

    return render_template('forgot_password.html', form=form, menu={})


@user_blueprint.route('/user/no_password.html', methods=['GET', 'POST'])
def no_password():
    form = NoPasswordForm(request.form)
    if form.validate_on_submit():

        user = models.Users.from_username_or_email(form.user.data)

        if not user:
            form.user.errors.append('Invalid username or email address.')
            return render_template('no_password.html', form=form, menu={})

        @after_app_teardown
        def send_activation():
            user.send_activation_email(next=request.args.get('next'))

        flash(
            'We sent a new activation email to your email address.', 'success')

        return redirect_back('index.index')

    return render_template('no_password.html', form=form, menu={})


@user_blueprint.route('/user/login_required')
@login_required
def test_login_required():
    return repr(current_user)


@user_blueprint.route(
    '/user/activate/<activation_hash>',
    methods=['GET', 'POST'])
def activation(activation_hash):
    form = NewPasswordForm(request.form)

    try:
        uid = models.serializer.loads(
            activation_hash, salt=models.ACTIVATION_SALT)
    except itsdangerous.BadSignature:
        abort(404)

    user = models.Users.from_id(uid)

    if not user:
        flash('Could not validate the request', 'error')
        abort(404)

    user.email_validation_change(True)

    if user.password:
        next = request.args.get('next')
        if not is_safe_url(next):
            abort(400)

        next = next or url_for('index.index')

        return render_template(
            'activation_with_password.html', next=next, menu={})

    if form.validate_on_submit():

        user.set_password(bcrypt.encrypt(form.password.data), True)

        login_user(user)

        return redirect(
            url_for(
                'user.activation',
                activation_hash=activation_hash,
                **request.args))

    next = request.args.get('next')
    return render_template(
        'activation_no_password.html',
        uid=uid, activation_hash=activation_hash, next=next, form=form,
        menu={})


@user_blueprint.route('/user/settings')
def settings():
    pass


@user_blueprint.route('/admin')
@login_required
def admin():
    """ dummy function to test a login_required call """
    return render_template('admin.html', menu={})

# vim:set ft=python sw=4 et spell spelllang=en:

app/flask_blog/templates/_bases/_base.html
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="{{config.META_DESCRIPTION}}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ config.TITLE }}</title>

    {% block above_the_fold_css %}
    {% endblock above_the_fold_css %}

    {% block head %}
    {% endblock head %}
  </head>
  <body>
<!-- Google Tag Manager -->
{% if config.GTM %}
<noscript><iframe src="//www.googletagmanager.com/ns.html?id={{ config.GTM }}"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','{{ config.GTM }}');</script>
{% endif %}
<!-- End Google Tag Manager -->
  {% block body %}

    <!--[if lt IE 10]>
      <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->


<div id="navbar">
  {% block navbar %}
  {% endblock navbar %}
</div>

<div id="header" class="container">
  {% block header %}
  <div id="upper_title" class="text-center">
    {% block upper_title %}
    {% endblock upper_title %}
  </div>
  {% endblock header %}
</div>

{% block flashes %}
{% with messages = get_flashed_messages(with_categories=true, category_filter=['error', 'success']) -%}
{% if messages -%}
{% for category, message in messages -%}
<div class="container">
  <div class="flash-messages">
    <div id="flash_message_{{loop.index}}" data-alert class="alert-box-{{category}}" tabindex="{{loop.index0}}" aria-live="assertive" role="dialogalert">
      {{ message }}
      <button href="#" tabindex="{{loop.index0}}" class="close" aria-label="Close Alert">&times;</button>
    </div>
  </div>
</div>
{% endfor -%}
{% endif -%}
{% endwith -%}
{% endblock flashes %}

<div id="content" class="container">
{% block content %}
{% endblock content %}
</div>

  {% block footer %}
  {% endblock footer %}

{% block foot %}
{% endblock foot %}

{% endblock body %}

</body>
</html>
{# vim:set et sw=2 ts=8 ft=htmljinja spell spelllang=en: #}

app/flask_blog/templates/_bases/_critical_path.html
{% extends "_bases/_headfoot_js.html" %}

{% block css %}
<script>
/*!
loadCSS: load a CSS file asynchronously.
[c]2014 @scottjehl, Filament Group, Inc.
Licensed MIT
 */

/* exported loadCSS */
function loadCSS( href, before, media, callback ){
  "use strict";
  // Arguments explained:
  // `href` is the URL for your CSS file.
  // `before` optionally defines the element we'll use as a reference for injecting our <link>
  // By default, `before` uses the first <script> element in the page.
  // However, since the order in which stylesheets are referenced matters, you might need a more specific location in your document.
  // If so, pass a different reference element to the `before` argument and it'll insert before that instead
  // note: `insertBefore` is used instead of `appendChild`, for safety re: http://www.paulirish.com/2011/surefire-dom-element-insertion/
  var ss = window.document.createElement( "link" );
  var ref = before || window.document.getElementsByTagName( "script" )[ 0 ];
  var sheets = window.document.styleSheets;
  ss.rel = "stylesheet";
  ss.href = href;
  // temporarily, set media to something non-matching to ensure it'll fetch without blocking render
  ss.media = "only x";
  // DEPRECATED
  if( callback ) {
    ss.onload = callback;
  }

  // inject link
  ref.parentNode.insertBefore( ss, ref );
  // This function sets the link's media back to `all` so that the stylesheet applies once it loads
  // It is designed to poll until document.styleSheets includes the new sheet.
  ss.onloadcssdefined = function( cb ){
    var defined;
    for( var i = 0; i < sheets.length; i++ ){
      if( sheets[ i ].href && sheets[ i ].href === ss.href ){
        defined = true;
      }
    }
    if( defined ){
      cb();
    } else {
      setTimeout(function() {
        ss.onloadcssdefined( cb );
      });
    }
  };
  ss.onloadcssdefined(function() {
    ss.media = media || "all";
  });
  return ss;
}
</script>
{% endblock css %}

{# vim: set ft=htmljinja sw=2 et: #}

app/flask_blog/templates/_bases/_headfoot_js.html
{% extends "_bases/_base.html" -%}
{% block head -%}
    <link rel="apple-touch-icon" href="/static/images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/static/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/static/images/apple-touch-icon-114x114.png">
    <link href="{{url_for('blog.recent_feed')}}" type="application/atom+xml" rel="alternate" title="{{ config.TITLE }} ATOM Feed" />
    <link rel="shortcut icon" href="/static/images/favicon.ico">
    <link rel="canonical" href="{{request | make_canonical }}">

    {% block css %}
      <!-- build:css /static/styles/main.css media="all" async -->
      <link rel="stylesheet" href="/static_gen/styles/main.css" media="all" async />
      <!-- endbuild -->
    {% endblock css %}

    <!-- build:css /static/styles/vendor.css -->
    <!-- bower:css -->
    <!-- endbower -->
    <!-- endbuild -->

    {# <link rel="stylesheet" href="/bower_components/slick.js/slick/slick.css" media="all" async /> #}

    <script async src="/bower_components/modernizr/modernizr.js" media="all"></script>
{%- endblock head %}

{% block navbar %}
  <nav class="navbar navbar-default">
    {# choose container instead of container-fluid, for a menu that is not full-width #}
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{{url_for('index.index')}}">
          {#- uncomment for a brand image
          <img alt="Brand" src="..." />
          -#}
          {{config.TITLE}}</a>
      </div>

      <div class="collapse navbar-collapse" id="main-navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          {% if current_user.is_authenticated() %}
          <!--        <li>
            <a href="{{url_for('user.settings')}}">My Account</a>
            </li> -->
            <li>
              <a href="{{url_for('user.logout')}}">Logout</a>
            </li>
            {% else %}
            <li>
              <a href="{{url_for('user.login')}}">Login</a>
            </li>
            <li>
              <a href="{{url_for('user.signup')}}">Sign Up</a>
            </li>
            {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-left">
          {# <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> #}
          <li class="dropdown {% if menu.select == 'blogs' %}active{% endif%}">
            <a href="{{url_for('blog.category_listing')}}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blogs <span class="caret"></span></a>

            <ul class="dropdown-menu">
              {% for slug, cat_name in blogs.get_categories().iteritems() %}
              <li class="{% if (category == slug) %}active{% endif %}">
                <a href="{{url_for('blog.category_listing', category=slug)}}">{{cat_name}}</a>
              </li>
              {% endfor %}
              {#-
              <li role="separator" class="divider">
              #}
            </ul>
          </li>
        </ul>
      </div>

    </div>
  </nav>
{% endblock navbar %}

<hr />
{% block footer %}
  <div id="footer" class="footer container">
    <div class="row">
      <section class="info">
        <p class="logo">
        {{ config.COPYRIGHT | safe }}
        </p>
        <p class="footer-links">
        <a href="{{url_for('index.index')}}">Home</a>
        <a href="{{url_for('blog.category_listing')}}">Blog</a>
        </p>
      </section>
      <section class="social">
        <p class="about">{{config.TITLE}}</p>
        <p class="about subheader">{{config.HEADLINE}}</p>

        <ul class="inline-list social">

          <a href="{{config.SOCIAL.facebook.url}}"><i class="fa fa-facebook"></i></a>
          <a href="http://www.twitter.com/{{config.SOCIAL.twitter.handle}}"><i class="fa fa-twitter"></i></a>
          <a href="mailto:{{config.CONTACT_email}}"><i class="fa fa-mail"></i></a>
        </ul>
      </section>
      <section class="contact text-center">
        <div class="contact">
          <a href="{{url_for('index.contact')}}">Write me</a>
        </div>
      </section>
    </div>
  </div>
{% endblock footer %}

{% block foot %}
  <script src="/bower_components/jquery/dist/jquery.js"></script>
  <script src="/bower_components/fastclick/lib/fastclick.js"></script>
  <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap.js"></script>
  {# uncomment if you want to use a flexible carousel
  <script src="/bower_components/slick.js/slick/slick.js"></script> #}

  <!-- build:js /static/scripts/main.js -->
  <script src="/static/scripts/main.js"></script>
  <!-- endbuild -->
{% endblock foot %}
</body>
</html>